export interface CityConfig {
  slug: string;
  displayName: string;
  kalshiSeriesTicker: string;
  latitude: number;
  longitude: number;
  timezone: string;
  nwsOffice: string;
  nwsGridX: number;
  nwsGridY: number;
  // Sigma (std dev in °F) for forecast error by days ahead
  sigmaDays: [number, number, number]; // [day1, day2, day3+]
}

export const CITIES: CityConfig[] = [
  {
    slug: "nyc",
    displayName: "New York City",
    kalshiSeriesTicker: "KXHIGHNY",
    latitude: 40.7128,
    longitude: -74.006,
    timezone: "America/New_York",
    nwsOffice: "OKX",
    nwsGridX: 33,
    nwsGridY: 37,
    sigmaDays: [3.0, 5.0, 6.0],
  },
  {
    slug: "chicago",
    displayName: "Chicago",
    kalshiSeriesTicker: "KXHIGHCHI",
    latitude: 41.8781,
    longitude: -87.6298,
    timezone: "America/Chicago",
    nwsOffice: "LOT",
    nwsGridX: 65,
    nwsGridY: 76,
    sigmaDays: [3.5, 5.5, 6.5],
  },
  {
    slug: "la",
    displayName: "Los Angeles",
    kalshiSeriesTicker: "KXHIGHLAX",
    latitude: 34.0522,
    longitude: -118.2437,
    timezone: "America/Los_Angeles",
    nwsOffice: "LOX",
    nwsGridX: 154,
    nwsGridY: 44,
    sigmaDays: [2.5, 4.0, 5.0],
  },
  {
    slug: "miami",
    displayName: "Miami",
    kalshiSeriesTicker: "KXHIGHMIA",
    latitude: 25.7617,
    longitude: -80.1918,
    timezone: "America/New_York",
    nwsOffice: "MFL",
    nwsGridX: 75,
    nwsGridY: 53,
    sigmaDays: [2.0, 3.5, 4.5],
  },
  {
    slug: "denver",
    displayName: "Denver",
    kalshiSeriesTicker: "KXHIGHDEN",
    latitude: 39.7392,
    longitude: -104.9903,
    timezone: "America/Denver",
    nwsOffice: "BOU",
    nwsGridX: 62,
    nwsGridY: 60,
    sigmaDays: [4.0, 6.0, 7.0],
  },
  {
    slug: "austin",
    displayName: "Austin",
    kalshiSeriesTicker: "KXHIGHAUS",
    latitude: 30.2672,
    longitude: -97.7431,
    timezone: "America/Chicago",
    nwsOffice: "EWX",
    nwsGridX: 116,
    nwsGridY: 92,
    sigmaDays: [3.0, 5.0, 6.0],
  },
  {
    slug: "boston",
    displayName: "Boston",
    kalshiSeriesTicker: "KXHIGHTBOS",
    latitude: 42.3601,
    longitude: -71.0589,
    timezone: "America/New_York",
    nwsOffice: "BOX",
    nwsGridX: 71,
    nwsGridY: 101,
    sigmaDays: [3.0, 5.0, 6.0],
  },
  {
    slug: "dc",
    displayName: "Washington DC",
    kalshiSeriesTicker: "KXHIGHTDC",
    latitude: 38.9072,
    longitude: -77.0369,
    timezone: "America/New_York",
    nwsOffice: "LWX",
    nwsGridX: 96,
    nwsGridY: 72,
    sigmaDays: [3.0, 5.0, 6.0],
  },
  {
    slug: "neworleans",
    displayName: "New Orleans",
    kalshiSeriesTicker: "KXHIGHTNOLA",
    latitude: 29.9511,
    longitude: -90.0715,
    timezone: "America/Chicago",
    nwsOffice: "LIX",
    nwsGridX: 68,
    nwsGridY: 88,
    sigmaDays: [2.5, 4.0, 5.0],
  },
  {
    slug: "phoenix",
    displayName: "Phoenix",
    kalshiSeriesTicker: "KXHIGHTPHX",
    latitude: 33.4484,
    longitude: -112.074,
    timezone: "America/Phoenix",
    nwsOffice: "PSR",
    nwsGridX: 159,
    nwsGridY: 58,
    sigmaDays: [2.5, 4.0, 5.0],
  },
  {
    slug: "seattle",
    displayName: "Seattle",
    kalshiSeriesTicker: "KXHIGHTSEA",
    latitude: 47.6062,
    longitude: -122.3321,
    timezone: "America/Los_Angeles",
    nwsOffice: "SEW",
    nwsGridX: 125,
    nwsGridY: 68,
    sigmaDays: [2.5, 4.0, 5.0],
  },
  {
    slug: "houston",
    displayName: "Houston",
    kalshiSeriesTicker: "KXHIGHTHOU",
    latitude: 29.7604,
    longitude: -95.3698,
    timezone: "America/Chicago",
    nwsOffice: "HGX",
    nwsGridX: 63,
    nwsGridY: 95,
    sigmaDays: [2.5, 4.0, 5.0],
  },
  {
    slug: "sanantonio",
    displayName: "San Antonio",
    kalshiSeriesTicker: "KXHIGHTSATX",
    latitude: 29.4241,
    longitude: -98.4936,
    timezone: "America/Chicago",
    nwsOffice: "EWX",
    nwsGridX: 126,
    nwsGridY: 54,
    sigmaDays: [2.5, 4.0, 5.0],
  },
  {
    slug: "vegas",
    displayName: "Las Vegas",
    kalshiSeriesTicker: "KXHIGHTLV",
    latitude: 36.1699,
    longitude: -115.1398,
    timezone: "America/Los_Angeles",
    nwsOffice: "VEF",
    nwsGridX: 123,
    nwsGridY: 98,
    sigmaDays: [2.5, 4.0, 5.0],
  },
  {
    slug: "sf",
    displayName: "San Francisco",
    kalshiSeriesTicker: "KXHIGHTSFO",
    latitude: 37.7749,
    longitude: -122.4194,
    timezone: "America/Los_Angeles",
    nwsOffice: "MTR",
    nwsGridX: 85,
    nwsGridY: 105,
    sigmaDays: [2.5, 4.0, 5.0],
  },
  {
    slug: "atlanta",
    displayName: "Atlanta",
    kalshiSeriesTicker: "KXHIGHTATL",
    latitude: 33.749,
    longitude: -84.388,
    timezone: "America/New_York",
    nwsOffice: "FFC",
    nwsGridX: 51,
    nwsGridY: 87,
    sigmaDays: [3.0, 5.0, 6.0],
  },
  {
    slug: "dallas",
    displayName: "Dallas",
    kalshiSeriesTicker: "KXHIGHTDAL",
    latitude: 32.7767,
    longitude: -96.797,
    timezone: "America/Chicago",
    nwsOffice: "FWD",
    nwsGridX: 89,
    nwsGridY: 104,
    sigmaDays: [3.0, 5.0, 6.0],
  },
  {
    slug: "okc",
    displayName: "Oklahoma City",
    kalshiSeriesTicker: "KXHIGHTOKC",
    latitude: 35.4676,
    longitude: -97.5164,
    timezone: "America/Chicago",
    nwsOffice: "OUN",
    nwsGridX: 97,
    nwsGridY: 94,
    sigmaDays: [3.5, 5.5, 6.5],
  },
  {
    slug: "minneapolis",
    displayName: "Minneapolis",
    kalshiSeriesTicker: "KXHIGHTMIN",
    latitude: 44.9778,
    longitude: -93.265,
    timezone: "America/Chicago",
    nwsOffice: "MPX",
    nwsGridX: 108,
    nwsGridY: 72,
    sigmaDays: [3.5, 5.5, 6.5],
  },
  {
    slug: "philadelphia",
    displayName: "Philadelphia",
    kalshiSeriesTicker: "KXHIGHPHIL",
    latitude: 39.9526,
    longitude: -75.1652,
    timezone: "America/New_York",
    nwsOffice: "PHI",
    nwsGridX: 50,
    nwsGridY: 76,
    sigmaDays: [3.0, 5.0, 6.0],
  },
];

// Lookup helpers
export function getCityBySlug(slug: string): CityConfig | undefined {
  return CITIES.find((c) => c.slug === slug);
}

export function getCityByTicker(ticker: string): CityConfig | undefined {
  return CITIES.find((c) => c.kalshiSeriesTicker === ticker);
}
